// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sources.Data;

#nullable disable

namespace Sources.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816232429_AddBorrowRequestUniqueActiveIndex")]
    partial class AddBorrowRequestUniqueActiveIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Sources.Models.ActivityUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConversionToBq")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityUnits");
                });

            modelBuilder.Entity("Sources.Models.AlertNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("Sources.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Sources.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Sources.Models.BorrowRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApproverUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BorrowerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReturnedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("BorrowerUserId");

                    b.HasIndex("ReturnedByUserId");

                    b.HasIndex("SourceId")
                        .IsUnique()
                        .HasFilter("Status IN ('Delivered', 'Overdue')");

                    b.ToTable("BorrowRequests");
                });

            modelBuilder.Entity("Sources.Models.GammaLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<double?>("Intensity")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RadioisotopeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Energy");

                    b.HasIndex("RadioisotopeId");

                    b.ToTable("GammaLines");
                });

            modelBuilder.Entity("Sources.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Sources.Models.Radioisotope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Energy")
                        .HasColumnType("REAL");

                    b.Property<string>("EnglishNotes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExemptionLimit")
                        .HasColumnType("REAL");

                    b.Property<double>("HalfLife")
                        .HasColumnType("REAL");

                    b.Property<string>("HalfLifeUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RadiationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Yield")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Radioisotopes");
                });

            modelBuilder.Entity("Sources.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Sources.Models.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentActivityUnitId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentActivityValue")
                        .HasColumnType("REAL");

                    b.Property<bool>("HasDetailedIsotopes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitialActivityUnitId")
                        .HasColumnType("TEXT");

                    b.Property<double>("InitialActivityValue")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RadioisotopeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentActivityUnitId");

                    b.HasIndex("InitialActivityUnitId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RadioisotopeId");

                    b.HasIndex("SourceCode")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Sources.Models.SourceIsotope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivityUnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentActivityValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("InitialActivityValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RadioisotopeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityUnitId");

                    b.HasIndex("RadioisotopeId");

                    b.HasIndex("SourceId");

                    b.ToTable("SourceIsotopes");
                });

            modelBuilder.Entity("Sources.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEditor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sources.Models.AlertNotification", b =>
                {
                    b.HasOne("Sources.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Sources.Models.AuditLog", b =>
                {
                    b.HasOne("Sources.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sources.Models.BorrowRequest", b =>
                {
                    b.HasOne("Sources.Models.User", "ApproverUser")
                        .WithMany("BorrowRequestsAsApprover")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sources.Models.User", "BorrowerUser")
                        .WithMany("BorrowRequestsAsBorrower")
                        .HasForeignKey("BorrowerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sources.Models.User", "ReturnedByUser")
                        .WithMany()
                        .HasForeignKey("ReturnedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sources.Models.Source", "Source")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("BorrowerUser");

                    b.Navigation("ReturnedByUser");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Sources.Models.GammaLine", b =>
                {
                    b.HasOne("Sources.Models.Radioisotope", "Radioisotope")
                        .WithMany("GammaLines")
                        .HasForeignKey("RadioisotopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radioisotope");
                });

            modelBuilder.Entity("Sources.Models.Source", b =>
                {
                    b.HasOne("Sources.Models.ActivityUnit", "CurrentActivityUnit")
                        .WithMany("SourcesCurrent")
                        .HasForeignKey("CurrentActivityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sources.Models.ActivityUnit", "InitialActivityUnit")
                        .WithMany("SourcesInitial")
                        .HasForeignKey("InitialActivityUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sources.Models.Location", "Location")
                        .WithMany("Sources")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sources.Models.Radioisotope", "Radioisotope")
                        .WithMany("Sources")
                        .HasForeignKey("RadioisotopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentActivityUnit");

                    b.Navigation("InitialActivityUnit");

                    b.Navigation("Location");

                    b.Navigation("Radioisotope");
                });

            modelBuilder.Entity("Sources.Models.SourceIsotope", b =>
                {
                    b.HasOne("Sources.Models.ActivityUnit", "ActivityUnit")
                        .WithMany()
                        .HasForeignKey("ActivityUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sources.Models.Radioisotope", "Radioisotope")
                        .WithMany()
                        .HasForeignKey("RadioisotopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sources.Models.Source", "Source")
                        .WithMany("SourceIsotopes")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityUnit");

                    b.Navigation("Radioisotope");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Sources.Models.User", b =>
                {
                    b.HasOne("Sources.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sources.Models.ActivityUnit", b =>
                {
                    b.Navigation("SourcesCurrent");

                    b.Navigation("SourcesInitial");
                });

            modelBuilder.Entity("Sources.Models.Location", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Sources.Models.Radioisotope", b =>
                {
                    b.Navigation("GammaLines");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Sources.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sources.Models.Source", b =>
                {
                    b.Navigation("BorrowRequests");

                    b.Navigation("SourceIsotopes");
                });

            modelBuilder.Entity("Sources.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BorrowRequestsAsApprover");

                    b.Navigation("BorrowRequestsAsBorrower");
                });
#pragma warning restore 612, 618
        }
    }
}
